### ISSUE TITLE
We should not be able to write alphabets in the text boxes

### ISSUE THREAD

**Issue by Dharmik48** [rutvikk05/tippy#1]
Currently, we can write alphabets in the _Bill Total_ and _Tip_ text boxes, which results in a `$NaN` output.

This is because the input boxes are of `type=text` we can change them to `type=number` to solve this.

I would like to work on this issue.

![image](https://user-images.githubusercontent.com/64529217/184582494-20a7ba7e-3bca-45d5-987e-76c0b157d4d6.png)

**Comment by rutvikk05** [comment]
Sure @Dharmik48! I've assigned it to you :)
