### ISSUE TITLE
Improvement: UI changes for the calculator.

### ISSUE THREAD

**Issue by DarkFalc0n** [rutvikk05/tippy#11]
The UI of the calculator can be improved to give it a frosted glass card look. Like this: 
![image](https://user-images.githubusercontent.com/59203815/196742223-f7f11f49-30af-4924-8588-cb2662b0c9d4.png)

**Comment by rutvikk05** [comment]
Sounds great! 
Good luck 🚀
Assigning it to you :)

**Comment by rutvikk05** [comment]
Thanks 👍
