### ISSUE TITLE
New feature: Spin bottle

### ISSUE THREAD

**Issue by taanii** [rutvikk05/tippy#17]
Spin the bottle will decide who will pay, so we can also add this feature for more payment options :D

**Comment by rutvikk05** [comment]
Haha sounds interesting! 
Wonder how it would like.
Would you like to work on this, @taanii ?

**Comment by taanii** [comment]
Yes, I'd like to work on this, but should we add it in same page or create a different page for it?

**Comment by rutvikk05** [comment]
How about a different page? 
It would help avoid congesting the current one!

**Comment by rutvikk05** [comment]
Good luck 🎉🚀

**Comment by taanii** [comment]
Thanks! @rutvikk05

**Comment by taanii** [comment]
@rutvikk05 Raised a [Pull Request for this issue](https://github.com/rutvikk05/tippy/pull/19) 
Pls check

**Comment by rutvikk05** [comment]
thnx for contributing!

**Comment by taanii** [comment]
Welcome! Grateful for the opportunity!
