### ISSUE TITLE
Use the all height of the screen size

### ISSUE THREAD

**Issue by jsapuyesp** [rutvikk05/tippy#24]
I see the app and i can see that 
![imagen](https://user-images.githubusercontent.com/47274649/197220761-b2d322bf-2091-42e2-bfea-81417a93d48d.png)

You are not using the full size of the screen in the app, and when i use a small screen i see this:
![imagen](https://user-images.githubusercontent.com/47274649/197220999-11a8bc05-248e-49b4-b968-2ec09384e29b.png)
 
Please asign to me this issue, i can fix it!

**Comment by rutvikk05** [comment]
Sure thing! 
Good luck 🤞

**Comment by tejus0** [comment]
Hey @rutvikk05 is this issue resolved? If not I can fix this issue.
