### ISSUE TITLE
Feature - Architecture of the project

### ISSUE THREAD

**Issue by jsapuyesp** [rutvikk05/tippy#27]
Hi, i have already worked in this project, and i suggest modify the folder of the project from: 

![imagen](https://user-images.githubusercontent.com/47274649/197373703-2592c7c3-2157-401d-8928-02729ac555bb.png)

to something like this:
![imagen](https://user-images.githubusercontent.com/47274649/197373742-0b0a0b1e-923c-40db-841c-9ed4ae37484f.png)

And the app still works!:
![imagen](https://user-images.githubusercontent.com/47274649/197374094-674cb5c3-24a4-449b-83ed-f305ebf18ca2.png)

I can send PR when you assign thiss issue to me...
Please asign to me this issue!

**Comment by rutvikk05** [comment]
Sure! Good luck @jsapuyesp 🤞

**Comment by jsapuyesp** [comment]
Can you add the hacktoberfest label?
