### ISSUE TITLE
Increment button (+), isn't increasing number of peoples.

### ISSUE THREAD

**Issue by Alok5102R** [rutvikk05/tippy#28]
Here's the issue description:

https://user-images.githubusercontent.com/56478877/197385867-087706ee-1c05-4c99-930e-be827591ca67.mp4

Also, it'll become easy for user, if we include submit button.

**Comment by rutvikk05** [comment]
Sure. Good luck 🤞

**Comment by Alok5102R** [comment]
I'd fixed the issue @rutvikk05 .
Have a look at PR #31

**Comment by Alok5102R** [comment]
I'd fixed merge conflicts @rutvikk05 
Now, you can merge PR #31
