### ISSUE TITLE
design a logo and add it to title bar

### ISSUE THREAD

**Issue by rutvikk05** [rutvikk05/tippy#3]

**Comment by MISSIC17** [comment]
I would like to help

**Comment by RachitGarg-12** [comment]
@rutvikk05 i would like to contribute to this.

**Comment by TenzinNsut** [comment]
Hey, rutvikk05 I would like to work on this issue. 
I can design and add the logo to your project.

**Comment by Tatwansh** [comment]
Hey, @rutvikk05 I would like to work on this issue to me.

**Comment by rutvikk05** [comment]
@MISSIC17 @Tatwansh @RachitGarg-12 @TenzinNsut 

Great to see your enthusiasm guys! 
This issue is open to all. Feel free to send your PR. 
I'll merge the best one :)

**Comment by TenzinNsut** [comment]
@rutvikk05  you want to add a favicon or a logo for "wrapper (class)" or both?

**Comment by TenzinNsut** [comment]
added logo and favicon, please check.

**Comment by rutvikk05** [comment]
Closing the issue. Thanks for contributing @TenzinNsut 🦸
