### ISSUE TITLE
Add a dark mode/light mode toggle

### ISSUE THREAD

**Issue by rutvikk05** [rutvikk05/tippy#4]
Add a toggle button to switch between light mode and dark mode.

**Comment by najeebkp** [comment]
hi @rutvikk05 please assign this to me

**Comment by rutvikk05** [comment]
Sure. Good luck 🤞

**Comment by rutvikk05** [comment]
Hey @najeebkp ! Great job so far. 
Just a request : 
Make sure to keep the current background as it is. 
When the user clicks the dark mode toggle, the background should change to a dark background ( anything except solid black). 
Good luck 🤞

**Comment by najeebkp** [comment]
oh ok. give me sometime.

**Comment by najeebkp** [comment]
please check
