### ISSUE TITLE
Input Buttons are misplaced

### ISSUE THREAD

**Issue by Milindcode** [rutvikk05/tippy#7]
Increment and Decrement buttons are placed in the middle of input box while they need to be toward right end.

Please assign it to me under hacktoberfest if  you find it valid.

![image](https://user-images.githubusercontent.com/91339883/196685837-3e320982-0ad3-49d1-8723-4cb136eff9d5.png)

**Comment by rutvikk05** [comment]
Thanks for pointing it out @Milindcode. 
Assigning it to you :)
