### ISSUE TITLE
Add sounds during increment/decrement 

### ISSUE THREAD

**Issue by rutvikk05** [rutvikk05/tippy#8]
Add sounds (maybe ca-ching 🤔) when incrementing or decrementing all the values !

**Comment by Rishabhraghwendra18** [comment]
Hi @rutvikk05 may I work on this issue ?

**Comment by rutvikk05** [comment]
Sure thing! Assigning it to you :)

**Comment by rutvikk05** [comment]
Would it be possible to reduce crop the length of soundtrack? 

Seems too lengthy :(
